// Generated by scripts/seed-prototype-assets.mjs
// Provider contracts are the seam between mock UX and real connectors.

import type { ProjectRequest } from '@/types/domain-models';

export type DataverseFieldRequiredLevel = 'none' | 'recommended' | 'application' | 'system';

export interface DataverseFieldMetadata {
  tableLogicalName: string;
  fieldLogicalName: string;
  displayName?: string;
  requiredLevel: DataverseFieldRequiredLevel;
  isRequired: boolean;
  maxLength?: number;   // String/Memo columns
  minValue?: number;    // Money/Decimal/Integer columns
  maxValue?: number;    // Money/Decimal/Integer columns
  precision?: number;   // Money/Decimal columns
}

export interface FieldMetadataRepository {
  getField(tableLogicalName: string, fieldLogicalName: string): Promise<DataverseFieldMetadata | null>;
}

export interface ProjectRequestRepository {
  list(): Promise<ProjectRequest[]>;
  getById(id: string): Promise<ProjectRequest | null>;
  save(input: Partial<ProjectRequest>): Promise<ProjectRequest>;
}

export interface AppDataProvider {
  projectRequests: ProjectRequestRepository;
  fieldMetadata: FieldMetadataRepository;
}
