// Generated by scripts/seed-prototype-assets.mjs
// Provider contracts are the seam between mock UX and real connectors.

import type { DemoDelivery } from '@/types/domain-models';
import type { DemoAsset } from '@/types/domain-models';
import type { DemoAssetUsage } from '@/types/domain-models';

export type DataverseFieldRequiredLevel = 'none' | 'recommended' | 'application' | 'system';

export interface DataverseFieldMetadata {
  tableLogicalName: string;
  fieldLogicalName: string;
  displayName?: string;
  requiredLevel: DataverseFieldRequiredLevel;
  isRequired: boolean;
  maxLength?: number;   // String/Memo columns
  minValue?: number;    // Money/Decimal/Integer columns
  maxValue?: number;    // Money/Decimal/Integer columns
  precision?: number;   // Money/Decimal columns
}

export interface FieldMetadataRepository {
  getField(tableLogicalName: string, fieldLogicalName: string): Promise<DataverseFieldMetadata | null>;
}

export interface DemoDeliveryRepository {
  list(): Promise<DemoDelivery[]>;
  getById(id: string): Promise<DemoDelivery | null>;
  save(input: Partial<DemoDelivery>): Promise<DemoDelivery>;
}

export interface DemoAssetRepository {
  list(): Promise<DemoAsset[]>;
  getById(id: string): Promise<DemoAsset | null>;
  save(input: Partial<DemoAsset>): Promise<DemoAsset>;
}

export interface DemoAssetUsageRepository {
  list(): Promise<DemoAssetUsage[]>;
  getById(id: string): Promise<DemoAssetUsage | null>;
  save(input: Partial<DemoAssetUsage>): Promise<DemoAssetUsage>;
}

export interface AppDataProvider {
  demoDeliveries: DemoDeliveryRepository;
  demoAssets: DemoAssetRepository;
  demoAssetUsages: DemoAssetUsageRepository;
  fieldMetadata: FieldMetadataRepository;
}
