// Generated by scripts/seed-prototype-assets.mjs
// Provides Dataverse column metadata (required level, maxLength, min/max/precision)
// backed by the generated service getMetadata() call.

import type { DataverseFieldMetadata, DataverseFieldRequiredLevel } from '@/services/data-contracts';

// ── RequiredLevel mapping (handles both string names and numeric values) ──

const BY_VALUE: Record<number, DataverseFieldRequiredLevel> = {
  0: 'none', 1: 'system', 2: 'application', 3: 'recommended',
};
const BY_NAME: Record<string, DataverseFieldRequiredLevel> = {
  none: 'none', systemrequired: 'system', applicationrequired: 'application', recommended: 'recommended',
};

export function mapRequiredLevel(value: unknown): DataverseFieldRequiredLevel {
  if (typeof value === 'number' && value in BY_VALUE) return BY_VALUE[value];
  if (typeof value === 'string') {
    const n = Number(value);
    if (Number.isFinite(n) && n in BY_VALUE) return BY_VALUE[n];
    const k = value.trim().toLowerCase();
    if (k in BY_NAME) return BY_NAME[k];
  }
  return 'none';
}

// ── Per-table metadata cache backed by getMetadata() ──

type AttributeRecord = Record<string, unknown>;

interface MetadataServiceEntry {
  getMetadata: (options: { schema: { columns: 'all' } }) => Promise<{
    data?: Partial<{ Attributes: AttributeRecord[] }>;
  }>;
}

// Register each table's generated service here after pac code add-data-source.
// Without an entry, metadata lookups for that table return null (no asterisks,
// no maxLength, no min/max).
export const metadataServiceRegistry: Record<string, MetadataServiceEntry> = {
  // Example after registering msfttrp_trips:
  // msfttrp_trips: Msfttrp_tripsService as unknown as MetadataServiceEntry,
};

const tableMetadataCache = new Map<string, Promise<Map<string, DataverseFieldMetadata>>>();

function fetchTableMetadata(tableLogicalName: string): Promise<Map<string, DataverseFieldMetadata>> {
  const cached = tableMetadataCache.get(tableLogicalName);
  if (cached) return cached;

  const service = metadataServiceRegistry[tableLogicalName];
  if (!service) {
    const empty = Promise.resolve(new Map<string, DataverseFieldMetadata>());
    tableMetadataCache.set(tableLogicalName, empty);
    return empty;
  }

  const promise = service
    .getMetadata({ schema: { columns: 'all' } })
    .then((result) => {
      const attributes = (result.data?.Attributes ?? []) as AttributeRecord[];
      const map = new Map<string, DataverseFieldMetadata>();

      for (const attr of attributes) {
        const logicalName = String(attr.LogicalName ?? '').toLowerCase();
        if (!logicalName) continue;

        const requiredLevelProp = attr.RequiredLevel as { Value?: unknown } | undefined;
        const requiredLevel = mapRequiredLevel(requiredLevelProp?.Value);
        const displayLabel = attr.DisplayName as { UserLocalizedLabel?: { Label?: string } } | undefined;

        map.set(logicalName, {
          tableLogicalName,
          fieldLogicalName: logicalName,
          displayName: displayLabel?.UserLocalizedLabel?.Label,
          requiredLevel,
          isRequired: requiredLevel === 'application' || requiredLevel === 'system',
          maxLength: typeof attr.MaxLength === 'number' ? attr.MaxLength : undefined,
          minValue: typeof attr.MinValue === 'number' ? attr.MinValue : undefined,
          maxValue: typeof attr.MaxValue === 'number' ? attr.MaxValue : undefined,
          precision: typeof attr.Precision === 'number' ? attr.Precision : undefined,
        });
      }
      return map;
    })
    .catch(() => new Map<string, DataverseFieldMetadata>());

  tableMetadataCache.set(tableLogicalName, promise);
  return promise;
}

export async function getFieldMetadata(
  tableLogicalName: string,
  fieldLogicalName: string,
): Promise<DataverseFieldMetadata | null> {
  const map = await fetchTableMetadata(tableLogicalName);
  return map.get(fieldLogicalName.toLowerCase()) ?? null;
}
