// Generated by scripts/seed-prototype-assets.mjs
import type { AppDataProvider } from '@/services/data-contracts';
import type { DemoDelivery } from '@/types/domain-models';
import type { DemoAsset } from '@/types/domain-models';
import type { DemoAssetUsage } from '@/types/domain-models';
import { mockDemoDeliverys } from '@/mockData/demoDelivery';
import { mockDemoAssets } from '@/mockData/demoAsset';
import { mockDemoAssetUsages } from '@/mockData/demoAssetUsage';

type PrototypeRecord = {
  id: string;
  name?: string;
};

function cloneRecord<T>(record: T): T {
  return JSON.parse(JSON.stringify(record)) as T;
}

function createCollectionRepository<T extends PrototypeRecord>(records: T[], buildFallbackName: () => string) {
  return {
    async list(): Promise<T[]> {
      return records.map((record) => cloneRecord(record));
    },
    async getById(id: string): Promise<T | null> {
      const record = records.find((item) => item.id === id);
      return record ? cloneRecord(record) : null;
    },
    async save(input: Partial<T>): Promise<T> {
      if (input.id) {
        const index = records.findIndex((record) => record.id === input.id);
        if (index >= 0) {
          records[index] = { ...records[index], ...input };
          return cloneRecord(records[index]);
        }
      }

      const record = {
        id: input.id || crypto.randomUUID(),
        name: input.name || buildFallbackName(),
        ...input,
      } as T;
      records.unshift(record);
      return cloneRecord(record);
    },
  };
}

export function createMockDataProvider(): AppDataProvider {
  const store = {
    demoDeliveries: mockDemoDeliverys.map((record) => cloneRecord(record)),
    demoAssets: mockDemoAssets.map((record) => cloneRecord(record)),
    demoAssetUsages: mockDemoAssetUsages.map((record) => cloneRecord(record)),
  };

  return {
    demoDeliveries: createCollectionRepository<DemoDelivery>(store.demoDeliveries, () => 'Demo Delivery Draft'),
    demoAssets: createCollectionRepository<DemoAsset>(store.demoAssets, () => 'Demo Asset Draft'),
    demoAssetUsages: createCollectionRepository<DemoAssetUsage>(store.demoAssetUsages, () => 'Demo Asset Usage Draft'),
    fieldMetadata: {
      async getField() { return null; },
    },
  } satisfies AppDataProvider;
}
