// Generated by scripts/seed-prototype-assets.mjs
import type { AppDataProvider } from '@/services/data-contracts';
import { createMockDataProvider } from '@/services/mock-data-provider';
import { createRealDataProvider } from '@/services/real-data-provider';

export function createAppDataProvider(): AppDataProvider {
  return import.meta.env.VITE_USE_MOCK === 'true'
    ? createMockDataProvider()
    : createRealDataProvider();
}
