// Generated by scripts/seed-prototype-assets.mjs
import type { AppDataProvider } from '@/services/data-contracts';
import { getFieldMetadata } from '@/services/field-metadata-cache';
import type { DemoDelivery } from '@/types/domain-models';
import type { DemoAsset } from '@/types/domain-models';
import type { DemoAssetUsage } from '@/types/domain-models';

// Replace the placeholder key mapping in this file after pac code add-data-source
// generates src/generated/** for your real connectors. Keep the UI-facing contract
// stable by adapting connector models into the domain models defined in src/types.

export function mapDemoDeliveryFromConnector(record: Record<string, unknown>): DemoDelivery {
  return {
    id: String(record.id ?? ''),
    name: String(record.name ?? ''),
    deliveryDate: String(record.deliveryDate ?? ''),
    customer: record.customer !== undefined ? String(record.customer) : undefined,
    presenter: record.presenter !== undefined ? String(record.presenter) : undefined,
    solutionArea: Number(record.solutionArea ?? 0),
    deliveryFormat: record.deliveryFormat !== undefined ? Number(record.deliveryFormat) : undefined,
    salesStage: record.salesStage !== undefined ? Number(record.salesStage) : undefined,
    outcome: record.outcome !== undefined ? Number(record.outcome) : undefined,
    audienceSize: record.audienceSize !== undefined ? Number(record.audienceSize) : undefined,
    assetGapReason: record.assetGapReason !== undefined ? Number(record.assetGapReason) : undefined,
    linkedAssetCount: record.linkedAssetCount !== undefined ? Number(record.linkedAssetCount) : undefined,
  };
}

export function mapDemoDeliveryToConnector(input: Partial<DemoDelivery>): Record<string, unknown> {
  return {
    ...(input.name !== undefined ? { name: input.name } : {}),
    ...(input.deliveryDate !== undefined ? { deliveryDate: input.deliveryDate } : {}),
    ...(input.customer !== undefined ? { customer: input.customer } : {}),
    ...(input.presenter !== undefined ? { presenter: input.presenter } : {}),
    ...(input.solutionArea !== undefined ? { solutionArea: input.solutionArea } : {}),
    ...(input.deliveryFormat !== undefined ? { deliveryFormat: input.deliveryFormat } : {}),
    ...(input.salesStage !== undefined ? { salesStage: input.salesStage } : {}),
    ...(input.outcome !== undefined ? { outcome: input.outcome } : {}),
    ...(input.audienceSize !== undefined ? { audienceSize: input.audienceSize } : {}),
    ...(input.assetGapReason !== undefined ? { assetGapReason: input.assetGapReason } : {}),
    ...(input.linkedAssetCount !== undefined ? { linkedAssetCount: input.linkedAssetCount } : {}),
  };
}

// Example once your generated service exists:
// import { DemoDeliveriesService } from '@/generated/services/DemoDeliveriesService';
// const result = await DemoDeliveriesService.getAll();
// return (result.data || []).map((record) => mapDemoDeliveryFromConnector(record as Record<string, unknown>));

export function mapDemoAssetFromConnector(record: Record<string, unknown>): DemoAsset {
  return {
    id: String(record.id ?? ''),
    name: String(record.name ?? ''),
    assetType: Number(record.assetType ?? 0),
    solutionArea: Number(record.solutionArea ?? 0),
    maturity: record.maturity !== undefined ? Number(record.maturity) : undefined,
    assetUrl: record.assetUrl !== undefined ? String(record.assetUrl) : undefined,
    description: record.description !== undefined ? String(record.description) : undefined,
    maintainer: record.maintainer !== undefined ? String(record.maintainer) : undefined,
    reuseCount: record.reuseCount !== undefined ? Number(record.reuseCount) : undefined,
    lastUsedOn: record.lastUsedOn !== undefined ? String(record.lastUsedOn) : undefined,
  };
}

export function mapDemoAssetToConnector(input: Partial<DemoAsset>): Record<string, unknown> {
  return {
    ...(input.name !== undefined ? { name: input.name } : {}),
    ...(input.assetType !== undefined ? { assetType: input.assetType } : {}),
    ...(input.solutionArea !== undefined ? { solutionArea: input.solutionArea } : {}),
    ...(input.maturity !== undefined ? { maturity: input.maturity } : {}),
    ...(input.assetUrl !== undefined ? { assetUrl: input.assetUrl } : {}),
    ...(input.description !== undefined ? { description: input.description } : {}),
    ...(input.maintainer !== undefined ? { maintainer: input.maintainer } : {}),
    ...(input.reuseCount !== undefined ? { reuseCount: input.reuseCount } : {}),
    ...(input.lastUsedOn !== undefined ? { lastUsedOn: input.lastUsedOn } : {}),
  };
}

// Example once your generated service exists:
// import { DemoAssetsService } from '@/generated/services/DemoAssetsService';
// const result = await DemoAssetsService.getAll();
// return (result.data || []).map((record) => mapDemoAssetFromConnector(record as Record<string, unknown>));

export function mapDemoAssetUsageFromConnector(record: Record<string, unknown>): DemoAssetUsage {
  return {
    id: String(record.id ?? ''),
    name: String(record.name ?? ''),
    demoDelivery: String(record.demoDelivery ?? ''),
    demoAsset: String(record.demoAsset ?? ''),
    usageNote: record.usageNote !== undefined ? String(record.usageNote) : undefined,
  };
}

export function mapDemoAssetUsageToConnector(input: Partial<DemoAssetUsage>): Record<string, unknown> {
  return {
    ...(input.name !== undefined ? { name: input.name } : {}),
    ...(input.demoDelivery !== undefined ? { demoDelivery: input.demoDelivery } : {}),
    ...(input.demoAsset !== undefined ? { demoAsset: input.demoAsset } : {}),
    ...(input.usageNote !== undefined ? { usageNote: input.usageNote } : {}),
  };
}

// Example once your generated service exists:
// import { DemoAssetUsagesService } from '@/generated/services/DemoAssetUsagesService';
// const result = await DemoAssetUsagesService.getAll();
// return (result.data || []).map((record) => mapDemoAssetUsageFromConnector(record as Record<string, unknown>));

export function createRealDataProvider(): AppDataProvider {
  return {
    demoDeliveries: {
      async list() {
        throw new Error('Implement demoDeliveries.list() in src/services/real-data-provider.ts using mapDemoDeliveryFromConnector()');
      },
      async getById() {
        throw new Error('Implement demoDeliveries.getById() in src/services/real-data-provider.ts using mapDemoDeliveryFromConnector()');
      },
      async save() {
        throw new Error('Implement demoDeliveries.save() in src/services/real-data-provider.ts using mapDemoDeliveryToConnector()');
      },
    },
    demoAssets: {
      async list() {
        throw new Error('Implement demoAssets.list() in src/services/real-data-provider.ts using mapDemoAssetFromConnector()');
      },
      async getById() {
        throw new Error('Implement demoAssets.getById() in src/services/real-data-provider.ts using mapDemoAssetFromConnector()');
      },
      async save() {
        throw new Error('Implement demoAssets.save() in src/services/real-data-provider.ts using mapDemoAssetToConnector()');
      },
    },
    demoAssetUsages: {
      async list() {
        throw new Error('Implement demoAssetUsages.list() in src/services/real-data-provider.ts using mapDemoAssetUsageFromConnector()');
      },
      async getById() {
        throw new Error('Implement demoAssetUsages.getById() in src/services/real-data-provider.ts using mapDemoAssetUsageFromConnector()');
      },
      async save() {
        throw new Error('Implement demoAssetUsages.save() in src/services/real-data-provider.ts using mapDemoAssetUsageToConnector()');
      },
    },
    fieldMetadata: { getField: getFieldMetadata },
  } satisfies AppDataProvider;
}
