// Generated by scripts/seed-prototype-assets.mjs
import type { AppDataProvider } from '@/services/data-contracts';
import { getFieldMetadata } from '@/services/field-metadata-cache';
import type { ProjectRequest } from '@/types/domain-models';

// Replace the placeholder key mapping in this file after pac code add-data-source
// generates src/generated/** for your real connectors. Keep the UI-facing contract
// stable by adapting connector models into the domain models defined in src/types.

export function mapProjectRequestFromConnector(record: Record<string, unknown>): ProjectRequest {
  return {
    id: String(record.id ?? ''),
    name: String(record.name ?? ''),
    requestStatus: Number(record.requestStatus ?? 0),
    requestedOn: record.requestedOn !== undefined ? String(record.requestedOn) : undefined,
  };
}

export function mapProjectRequestToConnector(input: Partial<ProjectRequest>): Record<string, unknown> {
  return {
    ...(input.name !== undefined ? { name: input.name } : {}),
    ...(input.requestStatus !== undefined ? { requestStatus: input.requestStatus } : {}),
    ...(input.requestedOn !== undefined ? { requestedOn: input.requestedOn } : {}),
  };
}

// Example once your generated service exists:
// import { ProjectRequestsService } from '@/generated/services/ProjectRequestsService';
// const result = await ProjectRequestsService.getAll();
// return (result.data || []).map((record) => mapProjectRequestFromConnector(record as Record<string, unknown>));

export function createRealDataProvider(): AppDataProvider {
  return {
    projectRequests: {
      async list() {
        throw new Error('Implement projectRequests.list() in src/services/real-data-provider.ts using mapProjectRequestFromConnector()');
      },
      async getById() {
        throw new Error('Implement projectRequests.getById() in src/services/real-data-provider.ts using mapProjectRequestFromConnector()');
      },
      async save() {
        throw new Error('Implement projectRequests.save() in src/services/real-data-provider.ts using mapProjectRequestToConnector()');
      },
    },
    fieldMetadata: { getField: getFieldMetadata },
  } satisfies AppDataProvider;
}
