// Generated by scripts/seed-prototype-assets.mjs
import type { ProjectRequest } from '@/types/domain-models';

export const mockProjectRequests: ProjectRequest[] = [
  {
    id: 'mock-projectRequests-1',
    name: 'Project Request 1',
    requestStatus: 100000000,
    requestedOn: '2026-03-01',
  },
  {
    id: 'mock-projectRequests-2',
    name: 'Project Request 2',
    requestStatus: 100000001,
    requestedOn: '2026-03-02',
  },
  {
    id: 'mock-projectRequests-3',
    name: 'Project Request 3',
    requestStatus: 100000002,
    requestedOn: '2026-03-03',
  },
];
