// Generated by scripts/seed-prototype-assets.mjs
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { createAppDataProvider } from '@/services/providerFactory';
import type { DemoDelivery } from '@/types/domain-models';
import type { DemoAsset } from '@/types/domain-models';
import type { DemoAssetUsage } from '@/types/domain-models';

const provider = createAppDataProvider();

export const prototypeQueryKeys = {
  demoDeliveries: ['demoDeliveries'] as const,
  demoDeliveryById: (id: string) => ['demoDeliveries', id] as const,
  demoAssets: ['demoAssets'] as const,
  demoAssetById: (id: string) => ['demoAssets', id] as const,
  demoAssetUsages: ['demoAssetUsages'] as const,
  demoAssetUsageById: (id: string) => ['demoAssetUsages', id] as const,
};

// ── Generic optimistic save hook ──
// Dataverse read replicas lag behind writes by up to several seconds.
// A naive invalidate-and-refetch pattern after a mutation will show stale data.
// This hook merges the user's input over the cache entry on success.

function useOptimisticSave<T extends { id: string }>({
  listKey, itemKey, saveFn,
}: {
  listKey: readonly string[];
  itemKey: (id: string) => readonly string[];
  saveFn: (input: Partial<T>) => Promise<T>;
}) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: saveFn,
    onMutate: async (input) => {
      await queryClient.cancelQueries({ queryKey: listKey });
      if (input.id) await queryClient.cancelQueries({ queryKey: itemKey(input.id) });
    },
    onSuccess: (serverRecord, input) => {
      const merged = input.id
        ? { ...(queryClient.getQueryData<T>(itemKey(input.id)) ?? serverRecord), ...input } as T
        : serverRecord;
      queryClient.setQueryData(itemKey(merged.id), merged);
      queryClient.setQueryData<T[]>(listKey, (old) => {
        if (!old) return [merged];
        const idx = old.findIndex((item) => item.id === merged.id);
        return idx >= 0
          ? old.map((item) => (item.id === merged.id ? merged : item))
          : [merged, ...old];
      });
    },
  });
}

export function useDemoDeliveries() {
  return useQuery({
    queryKey: prototypeQueryKeys.demoDeliveries,
    queryFn: () => provider.demoDeliveries.list(),
  });
}

export function useDemoDelivery(id: string | undefined) {
  return useQuery({
    queryKey: prototypeQueryKeys.demoDeliveryById(id || 'new'),
    queryFn: () => (id ? provider.demoDeliveries.getById(id) : Promise.resolve(null)),
    enabled: Boolean(id),
  });
}

export function useSaveDemoDelivery() {
  return useOptimisticSave<DemoDelivery>({
    listKey: prototypeQueryKeys.demoDeliveries,
    itemKey: prototypeQueryKeys.demoDeliveryById,
    saveFn: (input) => provider.demoDeliveries.save(input),
  });
}

export function useDemoAssets() {
  return useQuery({
    queryKey: prototypeQueryKeys.demoAssets,
    queryFn: () => provider.demoAssets.list(),
  });
}

export function useDemoAsset(id: string | undefined) {
  return useQuery({
    queryKey: prototypeQueryKeys.demoAssetById(id || 'new'),
    queryFn: () => (id ? provider.demoAssets.getById(id) : Promise.resolve(null)),
    enabled: Boolean(id),
  });
}

export function useSaveDemoAsset() {
  return useOptimisticSave<DemoAsset>({
    listKey: prototypeQueryKeys.demoAssets,
    itemKey: prototypeQueryKeys.demoAssetById,
    saveFn: (input) => provider.demoAssets.save(input),
  });
}

export function useDemoAssetUsages() {
  return useQuery({
    queryKey: prototypeQueryKeys.demoAssetUsages,
    queryFn: () => provider.demoAssetUsages.list(),
  });
}

export function useDemoAssetUsage(id: string | undefined) {
  return useQuery({
    queryKey: prototypeQueryKeys.demoAssetUsageById(id || 'new'),
    queryFn: () => (id ? provider.demoAssetUsages.getById(id) : Promise.resolve(null)),
    enabled: Boolean(id),
  });
}

export function useSaveDemoAssetUsage() {
  return useOptimisticSave<DemoAssetUsage>({
    listKey: prototypeQueryKeys.demoAssetUsages,
    itemKey: prototypeQueryKeys.demoAssetUsageById,
    saveFn: (input) => provider.demoAssetUsages.save(input),
  });
}
