// Generated by scripts/seed-prototype-assets.mjs
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { createAppDataProvider } from '@/services/providerFactory';
import type { ProjectRequest } from '@/types/domain-models';

const provider = createAppDataProvider();

export const prototypeQueryKeys = {
  projectRequests: ['projectRequests'] as const,
  projectRequestById: (id: string) => ['projectRequests', id] as const,
};

// ── Generic optimistic save hook ──
// Dataverse read replicas lag behind writes by up to several seconds.
// A naive invalidate-and-refetch pattern after a mutation will show stale data.
// This hook merges the user's input over the cache entry on success.

function useOptimisticSave<T extends { id: string }>({
  listKey, itemKey, saveFn,
}: {
  listKey: readonly string[];
  itemKey: (id: string) => readonly string[];
  saveFn: (input: Partial<T>) => Promise<T>;
}) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: saveFn,
    onMutate: async (input) => {
      await queryClient.cancelQueries({ queryKey: listKey });
      if (input.id) await queryClient.cancelQueries({ queryKey: itemKey(input.id) });
    },
    onSuccess: (serverRecord, input) => {
      const merged = input.id
        ? { ...(queryClient.getQueryData<T>(itemKey(input.id)) ?? serverRecord), ...input } as T
        : serverRecord;
      queryClient.setQueryData(itemKey(merged.id), merged);
      queryClient.setQueryData<T[]>(listKey, (old) => {
        if (!old) return [merged];
        const idx = old.findIndex((item) => item.id === merged.id);
        return idx >= 0
          ? old.map((item) => (item.id === merged.id ? merged : item))
          : [merged, ...old];
      });
    },
  });
}

export function useProjectRequests() {
  return useQuery({
    queryKey: prototypeQueryKeys.projectRequests,
    queryFn: () => provider.projectRequests.list(),
  });
}

export function useProjectRequest(id: string | undefined) {
  return useQuery({
    queryKey: prototypeQueryKeys.projectRequestById(id || 'new'),
    queryFn: () => (id ? provider.projectRequests.getById(id) : Promise.resolve(null)),
    enabled: Boolean(id),
  });
}

export function useSaveProjectRequest() {
  return useOptimisticSave<ProjectRequest>({
    listKey: prototypeQueryKeys.projectRequests,
    itemKey: prototypeQueryKeys.projectRequestById,
    saveFn: (input) => provider.projectRequests.save(input),
  });
}
