// Generated by scripts/seed-prototype-assets.mjs
// Edit dataverse/planning-payload.json, then rerun npm run prototype:seed to refresh.

export interface ProjectRequest {
  id: string;
  name: string;
  requestStatus: number;
  requestedOn?: string;
}
