// Generated by scripts/seed-prototype-assets.mjs
// Edit dataverse/planning-payload.json, then rerun npm run prototype:seed to refresh.

export interface DemoDelivery {
  id: string;
  name: string;
  deliveryDate: string;
  customer?: string;
  presenter?: string;
  solutionArea: number;
  deliveryFormat?: number;
  salesStage?: number;
  outcome?: number;
  audienceSize?: number;
  assetGapReason?: number;
  linkedAssetCount?: number;
}

export interface DemoAsset {
  id: string;
  name: string;
  assetType: number;
  solutionArea: number;
  maturity?: number;
  assetUrl?: string;
  description?: string;
  maintainer?: string;
  reuseCount?: number;
  lastUsedOn?: string;
}

export interface DemoAssetUsage {
  id: string;
  name: string;
  demoDelivery: string;
  demoAsset: string;
  usageNote?: string;
}
