// Generated by scripts/seed-prototype-assets.mjs
export const prototypeManifest = {
  generatedFrom: 'dataverse/planning-payload.json',
  feedbackPath: 'dataverse/prototype-feedback.md',
  entities: [
    {
      displayName: 'Demo Delivery',
      collectionName: 'demoDeliveries',
      description: 'A demo delivered by a seller to a customer on a date',
      mockDataFile: 'src/mockData/demoDelivery.ts',
      repositoryName: 'DemoDeliveryRepository',
    },
    {
      displayName: 'Demo Asset',
      collectionName: 'demoAssets',
      description: 'A reusable artifact that backs one or more demos; lives in a shared catalog',
      mockDataFile: 'src/mockData/demoAsset.ts',
      repositoryName: 'DemoAssetRepository',
    },
    {
      displayName: 'Demo Asset Usage',
      collectionName: 'demoAssetUsages',
      description: 'Junction record: a demo delivery reused a demo asset',
      mockDataFile: 'src/mockData/demoAssetUsage.ts',
      repositoryName: 'DemoAssetUsageRepository',
    },
  ],
} as const;
