// Generated by scripts/seed-prototype-assets.mjs
export const prototypeManifest = {
  generatedFrom: '\dataverse\planning-payload.json',
  feedbackPath: 'dataverse/prototype-feedback.md',
  entities: [
    {
      displayName: 'Project Request',
      collectionName: 'projectRequests',
      description: 'Tracks incoming requests for work',
      mockDataFile: 'src/mockData/projectRequest.ts',
      repositoryName: 'ProjectRequestRepository',
    },
  ],
} as const;
